/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import javax.swing.JOptionPane;

/**
 *
 * @author andres
 */
public class AdminIngresoProduct extends javax.swing.JFrame {

    /**
     * Creates new form AdminIngresoProduct
     */
    public AdminIngresoProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloAdminProd = new javax.swing.JLabel();
        lblNombreProdAdmin = new javax.swing.JLabel();
        txtNomProductAdmin = new javax.swing.JTextField();
        lblTipoProductoAdmin = new javax.swing.JLabel();
        cbxProductoAdmin = new javax.swing.JComboBox<>();
        lblMarcaAdmin = new javax.swing.JLabel();
        txtMarcaProdAdmin = new javax.swing.JTextField();
        lblDescProductoAdmin = new javax.swing.JLabel();
        txtDescripcionProductoAdmin = new javax.swing.JTextField();
        lblPrecioProdAdmin = new javax.swing.JLabel();
        txtPrecioProdAdmin = new javax.swing.JTextField();
        lblCantidadProductoAdmin = new javax.swing.JLabel();
        txtCantidadProductoAdmin = new javax.swing.JTextField();
        btnRegresarProductosAdmin = new javax.swing.JButton();
        btnGuardarProdAdmin = new javax.swing.JButton();
        lblMarcaIngresoProductos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTituloAdminProd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTituloAdminProd.setText("PRODUCT ENTRY");

        lblNombreProdAdmin.setText("Name Product");

        lblTipoProductoAdmin.setText("Tipe Product");

        cbxProductoAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select --", "Medicine", "Food", "Accessories" }));
        cbxProductoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoAdminActionPerformed(evt);
            }
        });

        lblMarcaAdmin.setText("Brand");

        txtMarcaProdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaProdAdminActionPerformed(evt);
            }
        });

        lblDescProductoAdmin.setText("Description");

        lblPrecioProdAdmin.setText("Price");

        lblCantidadProductoAdmin.setText("Quantity");

        btnRegresarProductosAdmin.setText("Return");
        btnRegresarProductosAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarProductosAdminActionPerformed(evt);
            }
        });

        btnGuardarProdAdmin.setText("Save Product");
        btnGuardarProdAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProdAdminActionPerformed(evt);
            }
        });

        lblMarcaIngresoProductos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblMarcaIngresoProductos.setText("InBodegas CKV - Huellitas CKV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(lblTituloAdminProd))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblPrecioProdAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblNombreProdAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNomProductAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTipoProductoAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMarcaAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblDescProductoAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtMarcaProdAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbxProductoAdmin, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescripcionProductoAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCantidadProductoAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtPrecioProdAdmin, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCantidadProductoAdmin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegresarProductosAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(btnGuardarProdAdmin)))
                .addGap(56, 56, 56))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMarcaIngresoProductos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(lblTituloAdminProd)
                .addGap(18, 18, 18)
                .addComponent(lblNombreProdAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomProductAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoProductoAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxProductoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblMarcaAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarcaProdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescProductoAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionProductoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecioProdAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioProdAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadProductoAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadProductoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarProductosAdmin)
                    .addComponent(btnGuardarProdAdmin))
                .addGap(32, 32, 32)
                .addComponent(lblMarcaIngresoProductos)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxProductoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProductoAdminActionPerformed

    private void txtMarcaProdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaProdAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaProdAdminActionPerformed

    private void btnRegresarProductosAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProductosAdminActionPerformed
        ViewInventarios inventAdmin = new ViewInventarios();
        inventAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarProductosAdminActionPerformed

    private void btnGuardarProdAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProdAdminActionPerformed
        // TODO add your handling code here:
        String nomProducto = txtNomProductAdmin.getText().trim();
        String tipProducto = (String) cbxProductoAdmin.getSelectedItem();
        String marca = txtMarcaProdAdmin.getText().trim();
        String detalle = txtDescripcionProductoAdmin.getText().trim();
        String precioTexto = txtPrecioProdAdmin.getText().trim();
        String cantidadTexto = txtCantidadProductoAdmin.getText().trim();

        if (!precioTexto.matches("\\d+") || !cantidadTexto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Price and Quantity must be valid numbers.");
            return;
        }

        int precio = Integer.parseInt(precioTexto);
        int cantidad = Integer.parseInt(cantidadTexto);
        int tProducto = 0;

        switch (tipProducto) {
            case "Food":
            tProducto = 1;
            break;
            case "Accessories":
            tProducto = 2;
            break;
            case "Medicine":
            tProducto = 3;
            break;
            default:
            break;
        }

        // Validar que los campos de texto no contengan caracteres especiales
        if (!nomProducto.matches("[a-zA-Z0-9\\s]+") || !marca.matches("[a-zA-Z0-9\\s]+") || !detalle.matches("[a-zA-Z0-9\\s]+")) {
            JOptionPane.showMessageDialog(this, "Name, Brand, and Description must not contain special characters.");
            return;
        }

        //Control de error para capos vacios o para loa campos precio, cantidad que reciban números
        if (nomProducto.isEmpty() || marca.isEmpty() || detalle.isEmpty() || precio <= 0 || cantidad <= 0 || tProducto <= 0 ) {
            StringBuilder errorMessage = new StringBuilder("The following fields cannot be empty:\n");

            if (nomProducto.isEmpty()) {
                errorMessage.append("- Name\n");
            }
            if (marca.isEmpty()) {
                errorMessage.append("- Brand\n");
            }
            if (detalle.isEmpty()) {
                errorMessage.append("- Description\n");
            }
            if (precio <= 0) {
                errorMessage.append("- Price must be a valid number\n");
            }
            if (cantidad <= 0) {
                errorMessage.append("- Quantity must be a valid integer\n");
            }
            if (tProducto <= 0 ) {
                errorMessage.append("- Type\n");
            }

            JOptionPane.showMessageDialog(this, errorMessage.toString().trim());
            return;
        }

        String mensaje;

        productosDao PD = new productosDao();
        Boolean respuesta = PD.createProduct(nomProducto, marca, detalle, precio, cantidad, tProducto);

        if (respuesta == true){
            mensaje = "Successful registration.";
            txtNomProductAdmin.setText("");
            txtMarcaProdAdmin.setText("");
            txtDescripcionProductoAdmin.setText("");
            txtPrecioProdAdmin.setText("");
            txtCantidadProductoAdmin.setText("");
            cbxProductoAdmin.setSelectedIndex(0);
        } else{
            mensaje = "It was not possible to register.";
        }

        JOptionPane.showMessageDialog(this,mensaje);
    }//GEN-LAST:event_btnGuardarProdAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminIngresoProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminIngresoProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminIngresoProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminIngresoProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminIngresoProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarProdAdmin;
    private javax.swing.JButton btnRegresarProductosAdmin;
    private javax.swing.JComboBox<String> cbxProductoAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadProductoAdmin;
    private javax.swing.JLabel lblDescProductoAdmin;
    private javax.swing.JLabel lblMarcaAdmin;
    private javax.swing.JLabel lblMarcaIngresoProductos;
    private javax.swing.JLabel lblNombreProdAdmin;
    private javax.swing.JLabel lblPrecioProdAdmin;
    private javax.swing.JLabel lblTipoProductoAdmin;
    private javax.swing.JLabel lblTituloAdminProd;
    private javax.swing.JTextField txtCantidadProductoAdmin;
    private javax.swing.JTextField txtDescripcionProductoAdmin;
    private javax.swing.JTextField txtMarcaProdAdmin;
    private javax.swing.JTextField txtNomProductAdmin;
    private javax.swing.JTextField txtPrecioProdAdmin;
    // End of variables declaration//GEN-END:variables
}
