/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import javax.swing.JOptionPane;

/**
 *
 * @author Fami VargasPreciado
 */
public class IngresoProductos extends javax.swing.JFrame {

    /**
     * Creates new form IngresoProductos
     */
    public IngresoProductos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomProduct = new javax.swing.JTextField();
        txtMarcaProd = new javax.swing.JTextField();
        txtDescripcionProducto = new javax.swing.JTextField();
        txtPrecioProd = new javax.swing.JTextField();
        txtCantidadProducto = new javax.swing.JTextField();
        lblNombreProd = new javax.swing.JLabel();
        lblTipoProducto = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDescProducto = new javax.swing.JLabel();
        lblPrecioProd = new javax.swing.JLabel();
        lblCantidadProducto = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<>();
        lblMarcaIngresoProductos = new javax.swing.JLabel();
        btnRegresarProductos = new javax.swing.JButton();
        btnGuardarProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("PRODUCT ENTRY");

        txtMarcaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaProdActionPerformed(evt);
            }
        });

        lblNombreProd.setText("Name Product");

        lblTipoProducto.setText("Tipe Product");

        jLabel4.setText("Brand");

        lblDescProducto.setText("Description");

        lblPrecioProd.setText("Price");

        lblCantidadProducto.setText("Quantity");

        cbxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select --", "Medicine", "Food", "Accessories" }));
        cbxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProductoActionPerformed(evt);
            }
        });

        lblMarcaIngresoProductos.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblMarcaIngresoProductos.setText("InBodegas CKV - Huellitas CKV");

        btnRegresarProductos.setText("Return");
        btnRegresarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarProductosActionPerformed(evt);
            }
        });

        btnGuardarProd.setText("Save Product");
        btnGuardarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMarcaIngresoProductos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblPrecioProd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreProd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomProduct, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTipoProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMarcaProd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbxProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, 237, Short.MAX_VALUE)
                                .addComponent(txtDescripcionProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCantidadProducto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrecioProd, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCantidadProducto, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegresarProductos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                                .addComponent(btnGuardarProd)))))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblNombreProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipoProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMarcaProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDescProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcionProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrecioProd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantidadProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarProductos)
                    .addComponent(btnGuardarProd))
                .addGap(6, 6, 6)
                .addComponent(lblMarcaIngresoProductos)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaProdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaProdActionPerformed

    private void btnRegresarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarProductosActionPerformed
        viewIncioUser inicioUser = new viewIncioUser();
        inicioUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarProductosActionPerformed

    private void btnGuardarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProdActionPerformed
        // TODO add your handling code here:
        String nomProducto = txtNomProduct.getText().trim();
        String tipProducto = (String) cbxProducto.getSelectedItem();
        String marca = txtMarcaProd.getText().trim();
        String detalle = txtDescripcionProducto.getText().trim();
        String precioTexto = txtPrecioProd.getText().trim();
        String cantidadTexto = txtCantidadProducto.getText().trim();
        
        if (!precioTexto.matches("\\d+") || !cantidadTexto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Price and Quantity must be valid numbers.");
            return;
        }
         
        int precio = Integer.parseInt(precioTexto);
        int cantidad = Integer.parseInt(cantidadTexto);
        int tProducto = 0;
        
        switch (tipProducto) {
            case "Food":
                tProducto = 1;
                break;
            case "Accessories":
                tProducto = 2;
                break;
            case "Medicine":
                tProducto = 3;
                break;
            default:
                break;
        }

           // Validar que los campos de texto no contengan caracteres especiales
        if (!nomProducto.matches("[a-zA-Z0-9\\s]+") || !marca.matches("[a-zA-Z0-9\\s]+") || !detalle.matches("[a-zA-Z0-9\\s]+")) {
            JOptionPane.showMessageDialog(this, "Name, Brand, and Description must not contain special characters.");
            return;
        }

        //Control de error para capos vacios o para loa campos precio, cantidad que reciban números
        if (nomProducto.isEmpty() || marca.isEmpty() || detalle.isEmpty() || precio <= 0 || cantidad <= 0 || tProducto <= 0 ) {
            StringBuilder errorMessage = new StringBuilder("The following fields cannot be empty:\n");

            if (nomProducto.isEmpty()) {
                errorMessage.append("- Name\n");
            }            
            if (marca.isEmpty()) {
                errorMessage.append("- Brand\n");
            }
            if (detalle.isEmpty()) {
                errorMessage.append("- Description\n");
            }
            if (precio <= 0) {
                errorMessage.append("- Price must be a valid number\n");
            } 
            if (cantidad <= 0) {
                errorMessage.append("- Quantity must be a valid integer\n");
            } 
            if (tProducto <= 0 ) {
                errorMessage.append("- Type\n");
            }

            JOptionPane.showMessageDialog(this, errorMessage.toString().trim());
            return;
        }
        
        String mensaje;
        
        productosDao PD = new productosDao();
        Boolean respuesta = PD.createProduct(nomProducto, marca, detalle, precio, cantidad, tProducto);
        
        if (respuesta == true){
            mensaje = "Successful registration.";
            txtNomProduct.setText("");
            txtMarcaProd.setText("");
            txtDescripcionProducto.setText("");
            txtPrecioProd.setText("");
            txtCantidadProducto.setText("");
            cbxProducto.setSelectedIndex(0);
        } else{
            mensaje = "It was not possible to register.";
        }
        
        JOptionPane.showMessageDialog(this,mensaje);
    }//GEN-LAST:event_btnGuardarProdActionPerformed

    private void cbxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProductoActionPerformed
    
    private void txtPrecioProdFocusLost(java.awt.event.FocusEvent evt) {
        // Verificar si el contenido del campo es un número
        String precioTexto = txtPrecioProd.getText().trim();

        if (!precioTexto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Price must be a valid number.", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            txtPrecioProd.requestFocusInWindow(); // Devolver el foco al campo de texto
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarProd;
    private javax.swing.JButton btnRegresarProductos;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidadProducto;
    private javax.swing.JLabel lblDescProducto;
    private javax.swing.JLabel lblMarcaIngresoProductos;
    private javax.swing.JLabel lblNombreProd;
    private javax.swing.JLabel lblPrecioProd;
    private javax.swing.JLabel lblTipoProducto;
    private javax.swing.JTextField txtCantidadProducto;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtMarcaProd;
    private javax.swing.JTextField txtNomProduct;
    private javax.swing.JTextField txtPrecioProd;
    // End of variables declaration//GEN-END:variables
}
