/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Fami VargasPreciado
 */
public class SalidaDeProductos extends javax.swing.JFrame {

    /**
     * Creates new form SalidaDeProductos
     */
    public SalidaDeProductos() {
        initComponents();
        llenarCbx();
        btnActualizarSalida.setEnabled(false);
        setLocationRelativeTo(null);

    }

    private DefaultListModel<String> modeloLista = new DefaultListModel<>();
    private DefaultComboBoxModel<String> comboBoxMarcas = new DefaultComboBoxModel<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lblSalidaDeProducto = new javax.swing.JLabel();
        lblCategoriaSalida = new javax.swing.JLabel();
        lblMarcaSalida = new javax.swing.JLabel();
        cbxCategoriaProducto = new javax.swing.JComboBox<>();
        cbxMarcaProductoSalida = new javax.swing.JComboBox<>();
        lblCantidadSalida = new javax.swing.JLabel();
        spnCantidadSalida = new javax.swing.JSpinner();
        btnRegresarSalida = new javax.swing.JButton();
        btnActualizarSalida = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListProductosSalida = new javax.swing.JList<>();
        btnBusqedaProductos = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSalidaDeProducto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSalidaDeProducto.setText("PRODUCT OUTPUT");

        lblCategoriaSalida.setText("Category");

        lblMarcaSalida.setText("Marca");

        cbxCategoriaProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select --", "Medicine", "Food", "Accessories" }));
        cbxCategoriaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaProductoActionPerformed(evt);
            }
        });

        cbxMarcaProductoSalida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbxMarcaProductoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMarcaProductoSalidaActionPerformed(evt);
            }
        });

        lblCantidadSalida.setText("Cantidad");

        btnRegresarSalida.setText("Return");
        btnRegresarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarSalidaActionPerformed(evt);
            }
        });

        btnActualizarSalida.setText("Update");
        btnActualizarSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarSalidaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListProductosSalida);

        btnBusqedaProductos.setText("Search");
        btnBusqedaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBusqedaProductosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnRegresarSalida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizarSalida)
                .addGap(72, 72, 72))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblCantidadSalida)
                        .addGap(32, 32, 32)
                        .addComponent(spnCantidadSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSalidaDeProducto)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblCategoriaSalida)
                                .addGap(18, 18, 18)
                                .addComponent(cbxCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(lblMarcaSalida)))
                        .addGap(18, 18, 18)
                        .addComponent(cbxMarcaProductoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(btnBusqedaProductos)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblSalidaDeProducto)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoriaSalida)
                    .addComponent(cbxCategoriaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarcaSalida)
                    .addComponent(cbxMarcaProductoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnBusqedaProductos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadSalida)
                    .addComponent(spnCantidadSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarSalida)
                    .addComponent(btnActualizarSalida))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCategoriaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCategoriaProductoActionPerformed

    private void btnRegresarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarSalidaActionPerformed
        viewIncioUser inicioUser = new viewIncioUser();
        inicioUser.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarSalidaActionPerformed

    private void btnActualizarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarSalidaActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> modeloLista = (DefaultListModel<String>) jListProductosSalida.getModel();

        // Verificar si se ha seleccionado un elemento en la lista
        if (jListProductosSalida.isSelectionEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a product from the list.", "Selection Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si no hay un producto seleccionado
        }
        
        // Obtener el valor seleccionado
        String valorSeleccionado = jListProductosSalida.getSelectedValue();
        Object valorSpinner = spnCantidadSalida.getValue();
        int valorEntero = (Integer) valorSpinner;
        
        if (valorEntero <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than zero.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si la cantidad es inválida
        }

        productosDao dao = new productosDao();

        // Llamar al método eliminarCantidad
        boolean actualizacionExitosa = dao.eliminarCantidad(valorSeleccionado, valorEntero);

        String mensaje;

        
        if (actualizacionExitosa) {
            mensaje = "Update successful.";
        } else {
            // Manejar el caso en que la actualización no fue exitosa
            mensaje = "It was not possible to register.";
        }

        JOptionPane.showMessageDialog(this, mensaje);
    }//GEN-LAST:event_btnActualizarSalidaActionPerformed

    private void btnBusqedaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBusqedaProductosActionPerformed
        // TODO add your handling code here:
        String tipProducto = (String) cbxCategoriaProducto.getSelectedItem();
        String marcaProducto = (String) cbxMarcaProductoSalida.getSelectedItem();

        if (tipProducto == null || tipProducto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a product category.", "Selection Error", JOptionPane.ERROR_MESSAGE);
            return; // Detener la ejecución si no hay una categoría seleccionada
        }
        
        int tProducto = 0;

        switch (tipProducto) {
            case "Food":
                tProducto = 1;
                break;
            case "Accessories":
                tProducto = 2;
                break;
            case "Medicine":
                tProducto = 3;
                break;
            default:
                break;
        }

        productosDao prodDTO = new productosDao();
        List<String> listaProductos = prodDTO.ListaNombresProductos(marcaProducto, tProducto);

        // Verificar si la lista de productos está vacía
        if (listaProductos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No products found for the selected criteria.", "No Results", JOptionPane.INFORMATION_MESSAGE);
            btnActualizarSalida.setEnabled(false);
            return; // Detener la ejecución si no hay productos para mostrar
        }
        
        // Limpiar el modelo de lista antes de agregar nuevos elementos
        modeloLista.clear();

        // Agregar los elementos de la lista obtenida de la base de datos al modelo de lista
        for (String nombreProducto : listaProductos) {
            modeloLista.addElement(nombreProducto);
        }

        // Asignar el modelo de lista al JList
        jListProductosSalida.setModel(modeloLista);
        
        if (jListProductosSalida != null) {
            btnActualizarSalida.setEnabled(true);
        }else{
            btnActualizarSalida.setEnabled(false);
        }
    }//GEN-LAST:event_btnBusqedaProductosActionPerformed

    private void cbxMarcaProductoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMarcaProductoSalidaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxMarcaProductoSalidaActionPerformed

    private void llenarCbx() {
        productosDao pDao = new productosDao();
        List<String> marcas = pDao.ListaMarcasProductos();

        // Verificar si la lista de marcas no está vacía
        if (!marcas.isEmpty()) {
            // Llenar el modelo con las marcas obtenidas
            for (String marca : marcas) {
                ((DefaultComboBoxModel<String>) comboBoxMarcas).addElement(marca);
            }

            // Establecer el nuevo modelo en el JComboBox
            cbxMarcaProductoSalida.setModel(comboBoxMarcas);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalidaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalidaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalidaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalidaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalidaDeProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarSalida;
    private javax.swing.JButton btnBusqedaProductos;
    private javax.swing.JButton btnRegresarSalida;
    private javax.swing.JComboBox<String> cbxCategoriaProducto;
    private javax.swing.JComboBox<String> cbxMarcaProductoSalida;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jListProductosSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCantidadSalida;
    private javax.swing.JLabel lblCategoriaSalida;
    private javax.swing.JLabel lblMarcaSalida;
    private javax.swing.JLabel lblSalidaDeProducto;
    private javax.swing.JSpinner spnCantidadSalida;
    // End of variables declaration//GEN-END:variables
}
